name: transmission-community
base: core22
adopt-info: transmission-community
summary: Lightweight FOSS Gtk Torrent Client.
description: |
  Transmission is a Lightweight and Powerful Bit-Torrent Client.
grade: stable
confinement: strict
compression: lzo
architectures:
  - build-on: amd64
    build-for: amd64
    
slots:
  transmission-community:
    interface: dbus
    bus: session
    name: org.transmission-gtk.community

apps:
  transmission-community:
    command: usr/local/bin/transmission-gtk
    extensions: [gnome]
    common-id: org.community.transmission
    environment:
            GTK_USE_PORTAL: 1
    plugs:
      - home
      - network
      - network-bind
      - raw-usb
      - removable-media
      - unity7
      - screen-inhibit-control
      - process-control
   
      

parts:
  transmission-community:
    source: https://github.com/transmission/transmission.git
    plugin: nil
    override-pull: |
      craftctl default
      craftctl set version=$(git describe --tags --abbrev=10) 
      
    build-packages:
      - curl
      - build-essential
      - automake
      - autoconf
      - libtool
      - pkg-config
      - intltool
      - libcurl4-openssl-dev
      - libglib2.0-dev
      - libevent-dev
      - libminiupnpc-dev
      - libgtk-3-dev
      - libappindicator3-dev
      - libssl-dev
    
    build-snaps:
      - cmake
      - ubuntu-make
      
    override-build: |
      craftctl default
      curl -LO https://github.com/transmission/transmission/releases/download/4.0.1/transmission-4.0.1.tar.xz
      tar xf transmission-4.0.1.tar.xz
      cd transmission-4.0.1
      mkdir build
      cd build 
      cmake -DCMAKE_BUILD_TYPE=RelWithDebInfo ..
      make -j$SNAPCRAFT_PARALLEL_BUILD_COUNT PREFIX=/usr
      make PREFIX=/usr DESTDIR=${SNAPCRAFT_PART_INSTALL} install
      
    stage-packages:
      - libminiupnpc17
